### ISSUE TITLE
Road to Declarative Usage

### ISSUE THREAD

**Issue by danrgll** [automl/neps#65]
Pipeline Space defined via yaml:
- [x] Hyperparameters are supported
- [ ] Architecture Parameters are not yet supported (See #66 )
  - see, example on how to use grammar search spaces with YAMLs [_TODO_]   
  	- Low priority until it's needed by someone or we have a clean Architecture Parameters setup that we can understand.
  	- TODO: Write up a simple example python file which we would like to be able to pass in and use.
- [ ] User Feedback: Store pipeline_space into yaml file with full description (See #84 )

`neps.run` arguments defined via yaml (using 'run_args'):
- [x] All arguments can be loaded via a yaml file (See #61 )
- Current Limitations:
  - [x] Strict usage of 'run_args' (See #67 )
  - [x] Missing documentation for Declarative Usage (See #68 )
  - [x] Enable argument modification for custom optimizer class that has been loaded via yaml (See #69 )
  - ~~[ ] ConfigSpace currently not supported via yaml~~
    - Not an intended usage 
  - [x] Using Custom optimizer via yaml currently only works if pipeline_space is also provided via yaml (See #87 )

- Improvements:
  - [x] Standardize yaml definitions for custom optimizer configurations (See #70 )
  - [x] Enable optional consolidation of multiple yaml files into one (See #73 )

Follow-up feature:
- [x] #74

Miscellaneous:
- [x] #86
